### ISSUE TITLE
'paytm/paytm-Swift.h' file not found     #import <paytm/paytm-Swift.h>

### ISSUE THREAD

**Issue by kkmadhpuriya** [mrdishant/Paytm-Flutter-Plugin#11]
i am getting this error.

Xcode's output:
↳
    === BUILD TARGET url_launcher OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/jyotsana/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/paytm-0.0.5/ios/Classes/PaytmPlugin.m:2:9: fatal error: 'paytm/paytm-Swift.h' file not found
    #import <paytm/paytm-Swift.h>

**Comment by mrdishant** [comment]
Try flutter clean then pod install (Delete PodFile.lock and PODS folder)
