### ISSUE TITLE
Storyboard doesn't contain a view controller with identifier 'FlutterViewController''

### ISSUE THREAD

**Issue by gssinghgautam** [mrdishant/Paytm-Flutter-Plugin#14]
Paytm Flutter 1.0.0
PaytmSdk FrameWork 5

Runner[5406:3635197] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Storyboard (<UIStoryboard: 0x600001b30c00>) doesn't contain a view controller with identifier 'FlutterViewController''

**Comment by mrdishant** [comment]
Change Main StoryBoard ViewController's identifier (Storyboard Id) to FlutterViewController

**Comment by gssinghgautam** [comment]
After doing that its shows a white screen when payment process is completed and payment flow tries to send response to the app

**Comment by wisecoders** [comment]
Same issue here. May I know what you did to fix the issue?

**Comment by mrdishant** [comment]
Plugin updated.
