### ISSUE TITLE
[QUESTION] I didn't understand why you have asked to pass PAYTM_MERCHANT_KEY

### ISSUE THREAD

**Issue by omishah** [mrdishant/Paytm-Flutter-Plugin#16]
I didn't understand why you have asked to pass PAYTM_MERCHANT_KEY to the checksum generator URL from the app? Isn't that unsafe to do so instead of storing the PAYTM_MERCHANT_KEY on our server?

**Comment by ankurpandeyvns** [comment]
Storing any credentials on the app is unsafe and even using the provided url for generating checksum isn't safe at all. You must always use your backend to generate the checksum for you.

**Comment by mrdishant** [comment]
@omishah  and @ankurpandeyvns  This  checksum generation url is just for testing and exploring Paytm.
I strongly agree to @ankurpandeyvns comment.
I am not storing any credentials on my server...

**Comment by omishah** [comment]
> @omishah and @ankurpandeyvns This checksum generation url is just for testing and exploring Paytm.
> I strongly agree to @ankurpandeyvns comment.
> I am not storing any credentials on my server...

I am not saying that you're storing any credentials on your server. Since you have mentioned in the readme/description part so I just said.
