### ISSUE TITLE
Issue with iOS

### ISSUE THREAD

**Issue by wisecoders** [mrdishant/Paytm-Flutter-Plugin#17]
Could you please compile the solution with Swift 5.1 compiler.

/Users/muthu/Documents/workspace/flutter/.pub-cache/hosted/pub.dartlang.org/paytm-1.0.0/ios/Classes/SwiftPaytmPlugin.swift:3:8: Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.1 compiler:

**Comment by mrdishant** [comment]
Plugin updated
