### ISSUE TITLE
issue in plugin integration in Ios

### ISSUE THREAD

**Issue by patidarmohit** [mrdishant/Paytm-Flutter-Plugin#2]
Hi,

Thanks for plugin. It is working perfectly in Android perfectly ...but  in iOS method invoke  "startPaytmPayment" not working....it says "No implementation found for  startPaytmPayment"

**Comment by kaumudpa** [comment]
@patidarmohit have you resolved this issue????

**Comment by mrdishant** [comment]
Plugin updated
