### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference

### ISSUE THREAD

**Issue by prashantspandey** [mrdishant/Paytm-Flutter-Plugin#20]
Hi , after generating the checksum, when I am calling Paytm.startPaytmPayment()
I get this errror:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference

Please solve this.

**Comment by mrdishant** [comment]
Plugin updated
