### ISSUE TITLE
Please update paytm library not abel to work witth latest swift library

### ISSUE THREAD

**Issue by Ravikumawat1990** [mrdishant/Paytm-Flutter-Plugin#23]
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.2.4 compiler: /

**Comment by Ravikumawat1990** [comment]
/Users/elixirtech/Desktop/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/paytm-1.0.0/ios/PaymentSDK.framework/PaymentSDK compiled with older version of Swift language (4.1/4.2) than previous files (5 or later) file '/Users/elixirtech/Desktop/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/paytm-1.0.0/ios/PaymentSDK.framework/PaymentSDK' for architecture x86_64

**Comment by mrdishant** [comment]
Hi Ravi
Plugin updated.
