### ISSUE TITLE
Paytm Integration issue, library is not working  for iOS app 

### ISSUE THREAD

**Issue by Ravikumawat1990** [mrdishant/Paytm-Flutter-Plugin#3]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Storyboard  (<UIStoryboard: 0x283cdbe80>) doesn't contain a view controller with identifier 'FlutterViewController''

**Comment by mrdishant** [comment]
![whatsapp image 2019-02-22 at 6 57 26 pm](https://user-images.githubusercontent.com/25786428/53346741-a7a66900-393d-11e9-89ab-ce941f659a1e.jpeg)
Just add "FlutterViewController" as Storyboard ID and Restoration Id for Main.storyboard's view controller.
