### ISSUE TITLE
You cannot change Callback url for production environment as it is in plugin or SDK

### ISSUE THREAD

**Issue by pawarmaheshkumar321** [mrdishant/Paytm-Flutter-Plugin#5]
I tried to change the callback url to production url from Paytm.dart or Startpayment.dart file but it keeps calling Staging environment url "https://securegw-stage.paytm.in/theia/processTransaction". It works nicely in Staging environment but cannot be used for production environment

**Comment by rdcoder33** [comment]
Hey, I have the same issue, can you tell me how you solved this?

**Comment by pawarmaheshkumar321** [comment]
while calling Paytm.startPaytmPayment method pass **testing** parameter value as **false**
like this

    var paytmResponse = Paytm.startPaytmPayment(
        false,
        mid,
        orderId,
        custid,
        chanelid,
        txnamt,
        website,
        callBackUrl,
        industrytype,
        checksum);

it calls production url if we pass the bool value as false
