### ISSUE TITLE
SWIFT VERSION ERROR FIX ASAP 

### ISSUE THREAD

**Issue by saikarthik952** [mrdishant/Paytm-Flutter-Plugin#6]
[!] Unable to determine Swift version for the following pods:

    - `paytm` does not specify a Swift version and none of the targets (`Runner`) integrating it
    have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION`
    attribute in at least one of the targets that integrate this pod.

**Comment by saikarthik952** [comment]
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler:
new ISSUE

**Comment by saikarthik952** [comment]
Ui is not detaching after transactions i mean it is not redirected to app flutter code

**Comment by mrdishant** [comment]
Unable to understand kindly email me at mr.dishantmahajan@gmail.com

**Comment by follow2vivek** [comment]
error: module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1.

**Comment by mrdishant** [comment]
Error Resolved New Version will be available in a week.

**Comment by Mahesh37** [comment]
Hi @mrdishant  the above error is still there. can you suggest us some detailed fix to this. Thanks for your good work.
