### ISSUE TITLE
not displaying login form and OTP process

### ISSUE THREAD

**Issue by sakshi1501** [mrdishant/Paytm-Flutter-Plugin#7]
I am running same code form your github code as well your merchant id and key and is working fine but when i am using my merchant id and key they directly redirect me to platform version and in my transaction it should be displaying failed or pending report

**Comment by mrdishant** [comment]
Not able to Understand
 Kindly Contact me on mr.dishantmahajan@gmail.com

**Comment by mrdishant** [comment]
Please check all other parameters Like APPSTAGING 
for me it's APPSTAGING your's can be WEBSTAGGING

Please Try and Tell me
