### ISSUE TITLE
After Payment complete it automatically move to my app splash screen.

### ISSUE THREAD

**Issue by Ravikumawat1990** [mrdishant/Paytm-Flutter-Plugin#9]

**Comment by mrdishant** [comment]
Please mail me at mr.dishantmahajan@gmail.com
We can discuss the issue there

**Comment by follow2vivek** [comment]
Same thing happen to me also, bro please make it stable.

**Comment by gssinghgautam** [comment]
I am facing the same issue

**Comment by mrdishant** [comment]
I am working on this. Issue solved. New Version will be available soon

**Comment by gssinghgautam** [comment]
@mrdishant can you please provide us with the timeline of the next release.

**Comment by mrdishant** [comment]
New Version will be available in a Week.

**Comment by gssinghgautam** [comment]
@mrdishant can you please do us a favour by releasing the version a bit early.

**Comment by gssinghgautam** [comment]
@mrdishant are you going to update this with new version or not.

**Comment by amitkhairnar44** [comment]
@gssinghgautam Have a look at this repo : https://github.com/iqans/flutter-paytm-webview
I have used similar approach and was able to get paytm working on android and ios. And I found that paytm uses webview in those plugins.

**Comment by ThakarRajesh** [comment]
I am facing same issue. please give us solution asap.

**Comment by mrdishant** [comment]
Plugin updated

**Comment by amitkhairnar44** [comment]
@mrdishant Instead of deleting comments and closing issues without any explanation why not redirect users to the new plugin?
